"""Initial migration - create tables

Revision ID: 8fe68fa46d2c
Revises: 
Create Date: 2025-11-11 14:04:56.614956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe68fa46d2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_id'), 'cache', ['id'], unique=False)
    op.create_index(op.f('ix_cache_key'), 'cache', ['key'], unique=True)
    op.create_table('extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('fetched_html_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source_used', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_id'), 'extractions', ['id'], unique=False)
    op.create_index(op.f('ix_extractions_url'), 'extractions', ['url'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strain_normalized', sa.String(), nullable=False),
    sa.Column('terp_vector', sa.JSON(), nullable=False),
    sa.Column('totals', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('extraction_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_strain_normalized'), 'profiles', ['strain_normalized'], unique=False)
    op.create_table('terpene_defs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effects', sa.JSON(), nullable=True),
    sa.Column('aroma', sa.String(), nullable=True),
    sa.Column('also_found_in', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terpene_defs_id'), 'terpene_defs', ['id'], unique=False)
    op.create_index(op.f('ix_terpene_defs_key'), 'terpene_defs', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terpene_defs_key'), table_name='terpene_defs')
    op.drop_index(op.f('ix_terpene_defs_id'), table_name='terpene_defs')
    op.drop_table('terpene_defs')
    op.drop_index(op.f('ix_profiles_strain_normalized'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_extractions_url'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_cache_key'), table_name='cache')
    op.drop_index(op.f('ix_cache_id'), table_name='cache')
    op.drop_table('cache')
    # ### end Alembic commands ###
